version: '3.8'
services:
  db:
    image: postgres:13
    container_name: auth-db-staging  
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    restart: unless-stopped   

  auth-service:
    image: abdum1964/auth-service:staging
    container_name: auth-service-staging   
       
    depends_on:
      -  db
    env_file:
      - .env   
    restart: unless-stopped 

volumes:
  postgres_data: