---
# AI-Assistant Service
- name: Check prerequisites
  command: "python3 {{ playbook_dir }}/prerequisite_check.py"
  register: prerequisites_check
  failed_when: prerequisites_check.rc != 0
  changed_when: false
  become: no

- name: Gather installed packages facts
  ansible.builtin.package_facts:
    manager: auto
  become: no

- name: Create project directory
  file:
    path: "{{ ansible_env.HOME }}/services/AI-Assistant"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: "{{ ansible_user_id | default(ansible_user) }}"
  become: no

- name: Clone the AI_Assistant repository
  git:
    repo: https://github.com/rejuve-bio/AI-Assistant.git
    dest: "{{ ansible_env.HOME }}/services/AI-Assistant"
    version: main
    force: yes
  become: no

- name: Copy pre-configured .env file to remote
  copy:
    src: templates/ai-assistant.env
    dest: "{{ ansible_env.HOME }}/services/AI-Assistant/.env"
    mode: '0640'
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: "{{ ansible_user_id | default(ansible_user) }}"
  become: no

- name: Run uv setup 
  command: uv run setup.py
  args:
    chdir: "{{ playbook_dir }}/.."
  become: no

# Docker Compose command detection
- name: Check for available Docker Compose command
  block:
    - name: Check if docker compose v2 is available
      command: docker compose version
      register: docker_compose_v2_check
      ignore_errors: yes
      changed_when: false
      become: no

    - name: Check if docker-compose v1 is available
      command: which docker-compose
      register: docker_compose_v1_check
      ignore_errors: yes
      changed_when: false
      become: no

    - name: Set compose command fact
      set_fact:
        docker_compose_command: "{{ 'docker compose' if docker_compose_v2_check.rc == 0 else 'docker-compose' if docker_compose_v1_check.rc == 0 else '' }}"
      become: no

    - name: Fail if no Docker Compose found
      fail:
        msg: "No Docker Compose command found. Please install either docker-compose v1 or docker compose v2."
      when: docker_compose_command == ''
      become: no

- name: Clean up existing containers
  shell: |
    sg docker -c "{{ docker_compose_command }} -f {{ ansible_env.HOME }}/services/AI-Assistant/docker-compose.yml down -v"
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: cleanup
  changed_when: "'Stopping' in cleanup.stdout"
  become: no

- name: Build and start containers
  shell: |
    sg docker -c "cd {{ ansible_env.HOME }}/services/AI-Assistant && {{ docker_compose_command }} up --build -d"
  args:
    executable: /bin/bash
  register: compose_up
  retries: 2
  delay: 10
  until: compose_up.rc == 0
  become: no

- name: Check AI Assistant main service container status
  docker_container_info:
    name: ai-assistant-assistant-1
  register: ai_assistant_service
  ignore_errors: yes
  become: no

- name: Check Qdrant container status
  docker_container_info:
    name: ai-assistant-qdrant-1
  register: qdrant_service
  ignore_errors: yes
  become: no

- name: Check Redis container status
  docker_container_info:
    name: ai-assistant-redis-1
  register: redis_service
  ignore_errors: yes
  become: no

- name: Print AI Assistant deployment status
  debug:
    msg: |
      {% if ai_assistant_service.container is defined and ai_assistant_service.container.State.Status == "running" and
            qdrant_service.container is defined and qdrant_service.container.State.Status == "running" and
            redis_service.container is defined and redis_service.container.State.Status == "running" %}
      ✅ AI Assistant service deployed successfully and running:
        - ai-assistant-assistant-1: http://localhost:5002
        - ai-assistant-qdrant-1: http://localhost:6333 (Dashboard), http://localhost:6334 (API)
        - ai-assistant-redis-1: redis://localhost:6378
      {% else %}
      ❌ Deployment incomplete: Some AI Assistant services are down.
        {% if ai_assistant_service.container is not defined or ai_assistant_service.container.State.Status != "running" %}
        - ai-assistant-assistant-1 is DOWN. Start with: {{ docker_compose_command }} up -d ai-assistant-assistant-1
        {% endif %}
        {% if qdrant_service.container is not defined or qdrant_service.container.State.Status != "running" %}
        - ai-assistant-qdrant-1 is DOWN. Start with: {{ docker_compose_command }} up -d ai-assistant-qdrant-1
        {% endif %}
        {% if redis_service.container is not defined or redis_service.container.State.Status != "running" %}
        - ai-assistant-redis-1 is DOWN. Start with: {{ docker_compose_command }} up -d ai-assistant-redis-1
        {% endif %}
      {% endif %}
  become: no