# Hypthesis Generation

- name: Check prerequisites
  command: "python3 {{ playbook_dir }}/prerequisite_check.py"
  register: prerequisites_check
  failed_when: prerequisites_check.rc != 0
  changed_when: false
  become: no  

- name: Ensure project directory exists
  file:
    path: "{{ ansible_env.HOME }}/services/Hypothesis"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: no  

- name: Clone Hypothesis repository
  git:
    repo: https://github.com/rejuve-bio/hypothesis-generation-demo.git
    dest: "{{ ansible_env.HOME }}/services/Hypothesis"
    version: main
    force: yes
  become: no

- name: Copy .env file
  template:
    src: ../templates/.env
    dest: "{{ ansible_env.HOME }}/services/Hypothesis/.env"
    mode: '0640'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: no

- name: Run uv setup 
  command: uv run setup.py
  args:
    chdir: "{{ playbook_dir }}/.."
  become: no

- name: Check for available Docker Compose command
  block:
    - name: Check if docker compose v2 is available
      command: docker compose version
      register: docker_compose_v2_check
      ignore_errors: yes
      changed_when: false
      become: no

    - name: Check if docker-compose v1 is available
      command: which docker-compose
      register: docker_compose_v1_check
      ignore_errors: yes
      changed_when: false
      become: no

    - name: Set compose command fact
      set_fact:
        docker_compose_command: "{{ 'docker compose' if docker_compose_v2_check.rc == 0 else 'docker-compose' if docker_compose_v1_check.rc == 0 else '' }}"
      become: no

    - name: Fail if no Docker Compose found
      fail:
        msg: "No Docker Compose command found. Please install either docker-compose v1 or docker compose v2."
      when: docker_compose_command == ''
      become: no

- name: Build and start containers
  shell: |
    sg docker -c "cd {{ ansible_env.HOME }}/services/Hypothesis && {{ docker_compose_command }} up --build -d"
  args:
    executable: /bin/bash
  register: compose_up
  retries: 2
  delay: 10
  until: compose_up.rc == 0
  become: no  # Run as user, sg docker handles group permissions